use std::ops::{Add, Neg, Sub};
use std::sync::{Arc, Mutex};
use std::sync::atomic::{AtomicBool, AtomicU64};
use std::time::Instant;
use usiagent::event::{UserEventDispatcher, UserEventQueue};
use usiagent::hash::KyokumenMap;
use usiagent::logger::Logger;
use usiagent::OnErrorHandler;
use usiagent::player::InfoSender;
use usiagent::rule::{AppliedMove, State};
use usiagent::shogi::{MochigomaCollections, ObtainKind, Teban};
use crate::error::ApplicationError;
use crate::solver::Solver;
